services:
  - type: web
    name: skillnotes
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: skillnotes-db
    databaseName: skillnotes
    user: skillnotes_user
